### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [BUIQUOCDAT1281997/grep#1]
1. Ваше приложение должно разбирать аргументы командной строки (массив `args`, переданный в `main`, а не строку введённую с консоли). Подумайте над использованием существующей библиотеки для этой задачи.
2. Зачем методы `numberLines`, `countMatches`, `positionLines`? Они в программе не используются.
3. Код методов `findContentFromPhrase`, `findContentIgnoreCase` и `invertsCondition` дублирует друг друга с небольшими отличиями. Подумайте, как его обобщить.
4. Полностью отсутствует поддержка регулярных выражений.
5. Есть гораздо более простой способ узнать, содержится ли подстрока в строке чем `split`.

**Comment by BUIQUOCDAT1281997** [comment]
я исправил

**Comment by gagarski** [comment]
1. Флаги командной строки могут сочетаться в любых комбинациях, у вас сейчас поддерживается только один флаг.
2. Передавать режим в виде строки - плохой стиль. Плюс см. замечание 1 из этого комментария.
3. Не надо проверять, что первый аргумент `crep`, более того его там быть не должно Попытайтесь понять, как работают консольные приложения и как в них передаются аргументы. Вам про это должны были рассказывать на лекции.
4. https://github.com/BUIQUOCDAT1281997/grep/blob/8563ba25529191bd3174ee61f6d1c0fb0349091c/src/Grep.java#L19
А если в `wordOrRegex` лежит `".*"`? Если хотите обобщить и преобразовывать слово к регексу, то подумайте, как это сделать правильно.

**Comment by BUIQUOCDAT1281997** [comment]
Мне второе замечание непонятно. Вы можете объяснить мне?

**Comment by gagarski** [comment]
То, что вы сделали следовало сделать с помощью перечислений (`enum`). Но с учётом написанного в первом замечании, вам придётся изменить логику и возможно второе замечание уже будет неактуально.

**Comment by BUIQUOCDAT1281997** [comment]
Значит , Если правильно исправить первое замечание , то второе замечание не обязательно исправить да?

**Comment by gagarski** [comment]
Смотря что у вас получится после исправления первого замечания.

**Comment by BUIQUOCDAT1281997** [comment]
мне понятно. спасибо Вам большое

**Comment by BUIQUOCDAT1281997** [comment]
Четвертое Замечание.
для каждого символа слова я довавлю []
пример: слово--->[с][л][о][в][о]
то правильно?

**Comment by BUIQUOCDAT1281997** [comment]
Я уже исправил. Вы Можете заранее проверить это задание?
я очень хочу сдать это задание до 15 апреля.
Please..

**Comment by gagarski** [comment]
> Четвертое Замечание.
для каждого символа слова я довавлю []
пример: слово--->[с][л][о][в][о]
то правильно?

Лучше сделать с помощью этого метода https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html#quote-java.lang.String-

Сейчас у вас проверка корректности аргументов неполноценна. Например  с аргументами `-r -i` программа запускается, но выдаёт исключение: `java.io.FileNotFoundException: -i (No such file or directory)`

Сделайте пожалуйста корректную проверку. Можете (и даже лучше) использовать библиотеку для разбора аргументов. Вам на лекции рассказывали как это сделать.

**Comment by BUIQUOCDAT1281997** [comment]
Но я не знаю , какую библиотеку для разбора аргументов нужно использовать

**Comment by BUIQUOCDAT1281997** [comment]
я придумал новый способ узнать, содержится ли подстрока в строке. И сделал корректную проверку.
Жду Ваши замечания.

**Comment by BUIQUOCDAT1281997** [comment]
Проверяйте пожалуйста мою работу. И дайте пожалуйста замечания, чтобы я исправил. я хочу заране сдать 1и 2 задания. я хочу пытаться сдавать срочный экзамен в 21/5.

**Comment by gagarski** [comment]
Мне всё ещё не нравится ваш разбор агрументов. При аргументах `-r -i gg.txt`, `-i` будет считаться регексом. Ещё раз рекомендую переделать как следует или использовать библиотеку (на лекции вам давили пример разбора с помощью библиотеки). Проверять имя файла на то, что он заканчивается на `txt` необязательно. Выбрасывать лучше не `Error`, а более специфичное исключение. 

Сравнение слова со строкой или регексом вы сделали более громоздко. 
Ещё раз:
 - чтобы экранировать специальные символы в строке можно использовать `Pattern.quote`
 - чтобы создать регекс можно вызвать `Pattern.compile`, с помощью этого метода регекс можно сделать нечувствительным к регистру. Дальше всем этим можно пользоваться вот так:
```
        Pattern p = Pattern.compile(thePattern, /* Pattern.CASE_INSENSITIVE если есть флаг -i */); // thePattern экранирован или не экранирован в зависимости от опций
        Matcher m = p.matcher(theString);
        boolean status = m.matches();
```

**Comment by BUIQUOCDAT1281997** [comment]
Сейчас мне уже понятно . я использовал библиотектки для разбора аргумента.
Спасибо Вам
